CREATE DATABASE Sales_Analytics;
USE Sales_Analytics;

-- CUSTOMERS TABLE :-
CREATE TABLE customers (
CustomerID INT PRIMARY KEY,
FirstName VARCHAR(50),
LastName VARCHAR(50),
Gender VARCHAR(10),
Age INT,
City VARCHAR(100),
State VARCHAR(100),
JoinDate DATE
);

-- PRODUCTS TABLE :-
CREATE TABLE products (
ProductID INT PRIMARY KEY,
ProductName VARCHAR(255),
Category VARCHAR(100),
Brand VARCHAR(100),
UnitCost DECIMAL(10,2),
UnitPrice DECIMAL(10,2)
);

-- ORDERS TABLE :-
CREATE TABLE orders (
OrderID INT PRIMARY KEY,
CustomerID INT,
SalesRepID INT,
OrderDate DATE,
PaymentMethod VARCHAR(50),
OrderStatus VARCHAR(50)
);

-- ORDER DETAILS TABLE :-
CREATE TABLE order_details (
OrderDetailID INT PRIMARY KEY,
OrderID INT,
ProductID INT,
Quantity INT,
DiscountPercent DECIMAL(5,2)
);

-- REGIONS TABLE :-
CREATE TABLE regions (
RegionID INT PRIMARY KEY,
RegionName VARCHAR(50)
);

-- SALES REPRESNETATIVES TABLE :-
CREATE TABLE sales_representatives (
SalesRepID INT PRIMARY KEY,
RepName VARCHAR(100),
RegionID INT,
HireDate DATE
);

-- ADDITION OF FOREIGN KEYS:-
ALTER TABLE orders
ADD CONSTRAINT fk_orders_customer
FOREIGN KEY (CustomerID)
REFERENCES customers(CustomerID);

ALTER TABLE orders
ADD CONSTRAINT fk_orders_salesrep
FOREIGN KEY (SalesRepID)
REFERENCES sales_representatives(SalesRepID);

ALTER TABLE order_details
ADD CONSTRAINT fk_orderdetails_order
FOREIGN KEY (OrderID)
REFERENCES orders(OrderID);

ALTER TABLE order_details
ADD CONSTRAINT fk_orderdetails_product
FOREIGN KEY (ProductID)
REFERENCES products(ProductID);

ALTER TABLE sales_representatives
ADD CONSTRAINT fk_salesrep_region
FOREIGN KEY (RegionID)
REFERENCES regions(RegionID);

SELECT COUNT(*) FROM customers;
SELECT COUNT(*) FROM products;
SELECT COUNT(*) FROM orders;
SELECT COUNT(*) FROM order_details;
SELECT COUNT(*) FROM regions;
SELECT COUNT(*) FROM sales_representatives;

SELECT * FROM customers;
SELECT * FROM products;
SELECT * FROM orders;
SELECT * FROM order_details;
SELECT * FROM regions;
SELECT * FROM sales_representatives;

/* 
   Analytical View: vw_sales

   Purpose:
   Create a business-ready analytical dataset by combining
   customers, products, orders, order details, sales
   representatives, and regions into a single view.

   Why this view is created:
   1. Simplifies SQL analysis by avoiding repeated JOINs.
   2. Ensures consistent calculations for revenue and profit.
   3. Reduces query complexity and improves readability.
   4. Acts as a centralized reporting layer for Excel,
      Power BI, and analytical queries.
   5. Mimics a real-world sales data mart used in analytics
      and business intelligence projects.

   Business Metrics Included:
   - GrossSales
   - DiscountAmount
   - NetSales
   - TotalCost
   - Profit

   Expected Outcome:
   A single analytical view that can be used for KPI reporting,
   trend analysis, product analysis, customer analysis, and
   dashboard development.
*/

USE Sales_Analytics;
USE sales_analytics;

CREATE OR REPLACE VIEW vw_sales AS
SELECT
    od.OrderDetailID,
    o.OrderID,
    o.OrderDate,
    o.PaymentMethod,
    o.OrderStatus,

    c.CustomerID,
    c.FirstName,
    c.LastName,
    c.Gender,
    c.Age,
    c.State,

    p.ProductID,
    p.ProductName,
    p.Category,
    p.Brand,

    sr.RepName,
    r.RegionName,

    od.Quantity,
    od.DiscountPercent,
    p.UnitPrice,
    p.UnitCost,

    -- Business Metrics
    (od.Quantity * p.UnitPrice) AS GrossSales,

    (od.Quantity * p.UnitPrice * od.DiscountPercent/100) AS DiscountAmount,

    (od.Quantity * p.UnitPrice * (1 - od.DiscountPercent/100)) AS NetSales,

    (od.Quantity * p.UnitCost) AS TotalCost,

    ((od.Quantity * p.UnitPrice * (1 - od.DiscountPercent/100))
     - (od.Quantity * p.UnitCost)) AS Profit

FROM order_details od
JOIN orders o ON od.OrderID = o.OrderID
JOIN customers c ON o.CustomerID = c.CustomerID
JOIN products p ON od.ProductID = p.ProductID
JOIN sales_representatives sr ON o.SalesRepID = sr.SalesRepID
JOIN regions r ON sr.RegionID = r.RegionID;

SELECT * FROM vw_sales LIMIT 10;
-- ==================================================================================================================

/* ============================================================
   Query 01: Total Revenue

   Business Question:
   What is the total revenue generated by the company?

   Objective:
   Measure overall sales performance across all transactions.

   Approach:
   Sum the NetSales value from the analytical view (vw_sales),
   where NetSales already accounts for discounts.

   Expected Outcome:
   Total Revenue = 169163902.87
============================================================ */

SELECT ROUND(SUM(NetSales), 2) AS TotalRevenue
FROM vw_sales;




/* ============================================================
   Query 02: Total Profit

   Business Question:
   How much profit has the company earned?

   Objective:
   Evaluate overall business profitability.

   Approach:
   Sum the Profit column, which is calculated as:
   NetSales - TotalCost.

   Expected Outcome:
   Total Profit = 44270425.29
============================================================ */

SELECT ROUND(SUM(Profit), 2) AS TotalProfit
FROM vw_sales;



/* ============================================================
   Query 03: Profit Margin Percentage

   Business Question:
   What percentage of revenue is retained as profit?

   Objective:
   Measure the efficiency and profitability of the business.

   Approach:
   Divide total profit by total revenue and multiply by 100.

   Expected Outcome:
   Profit Margin Percentage = 26.17%
   ============================================================ */

SELECT ROUND(
    SUM(Profit) / SUM(NetSales) * 100,
    2
) AS ProfitMarginPercent
FROM vw_sales;


/* ============================================================
   Query 04: Total Orders

   Business Question:
   How many unique orders were placed?

   Objective:
   Measure overall order volume.

   Approach:
   Count distinct OrderID values from the sales view.

   Expected Outcome:
   Total number of orders = 40000
============================================================ */

SELECT COUNT(DISTINCT OrderID) AS TotalOrders
FROM vw_sales;


/* ============================================================
   Query 05: Total Customers

   Business Question:
   How many customers have made purchases?

   Objective:
   Measure customer reach and business penetration.

   Approach:
   Count distinct CustomerID values from the sales view.

   Expected Outcome:
   Total number of purchasing customers = 13937
============================================================ */

SELECT COUNT(DISTINCT CustomerID) AS TotalCustomers
FROM vw_sales;


/* ============================================================
   Query 06: Total Units Sold

   Business Question:
   How many product units were sold?

   Objective:
   Measure sales volume across all products.

   Approach:
   Sum the Quantity column from the sales view.

   Expected Outcome:
   Total quantity of products sold = 301358
============================================================ */

SELECT SUM(Quantity) AS UnitsSold
FROM vw_sales;


/* ============================================================
   Query 07: Average Order Value (AOV)

   Business Question:
   How much revenue does an average order generate?

   Objective:
   Understand customer spending behavior per order.

   Approach:
   First calculate revenue for each order, then compute the
   average of all order revenues.

   Expected Outcome:
   Average revenue generated per order = 4229.10
============================================================ */

SELECT ROUND(
    AVG(OrderRevenue), 2
) AS AverageOrderValue
FROM (
    SELECT OrderID, SUM(NetSales) AS OrderRevenue
    FROM vw_sales
    GROUP BY OrderID
)t;




/* ============================================================
   Query 08: Monthly Revenue Trend

   Business Question:
   How has revenue changed over time?

   Objective:
   Identify growth patterns, seasonality, and high/low
   performing months.

   Approach:
   Group transactions by year and month and calculate total
   revenue for each period.

   Expected Outcome:
   A chronological monthly revenue trend.
============================================================ */

SELECT
    DATE_FORMAT(OrderDate, '%Y-%m') AS Month,
    ROUND(SUM(NetSales), 2) AS Revenue
FROM vw_sales
GROUP BY DATE_FORMAT(OrderDate, '%Y-%m')
ORDER BY Month;



/* ============================================================
   Query 09: Monthly Profit Trend

   Business Question:
   How has profitability changed over time?

   Objective:
   Track profit performance and identify months with unusually
   high or low profitability.

   Approach:
   Group transactions by month and calculate total profit.

   Expected Outcome:
   A monthly profit trend for profitability analysis.
============================================================ */

SELECT
    DATE_FORMAT(OrderDate, '%Y-%m') AS Month,
    ROUND(SUM(Profit), 2) AS Profit
FROM vw_sales
GROUP BY DATE_FORMAT(OrderDate, '%Y-%m')
ORDER BY Month;



/* ============================================================
   Query 10: Monthly Orders Trend

   Business Question:
   How has customer order volume changed over time?

   Objective:
   Analyze customer purchasing activity and business demand.

   Approach:
   Count distinct orders for each month.

   Expected Outcome:
   A monthly order trend showing transaction activity.
============================================================ */

SELECT
    DATE_FORMAT(OrderDate, '%Y-%m') AS Month,
    COUNT(DISTINCT OrderID) AS Orders
FROM vw_sales
GROUP BY DATE_FORMAT(OrderDate, '%Y-%m')
ORDER BY Month;



/* ============================================================
   Query 11: Top 10 Products by Revenue

   Business Question:
   Which products generate the highest revenue?

   Objective:
   Identify best-selling products and support inventory,
   pricing, and marketing decisions.

   Approach:
   Aggregate revenue by product and sort in descending order.

   Expected Outcome:
   Top 10 revenue-generating products.
============================================================ */

SELECT
    ProductName,
    ROUND(SUM(NetSales), 2) AS Revenue,
    SUM(Quantity) AS UnitsSold,
    ROUND(SUM(Profit), 2) AS Profit
FROM vw_sales
GROUP BY ProductName
ORDER BY Revenue DESC
LIMIT 10;



/* ============================================================
   Query 12: Revenue by Category

   Business Question:
   Which product categories contribute the most revenue?

   Objective:
   Compare category performance and identify the strongest
   business segments.

   Approach:
   Group transactions by Category and calculate total revenue.

   Expected Outcome:
   Revenue contribution of each product category.
============================================================ */

SELECT
    Category,
    ROUND(SUM(NetSales), 2) AS Revenue,
    SUM(Quantity) AS UnitsSold,
    COUNT(DISTINCT ProductID) AS ProductCount
FROM vw_sales
GROUP BY Category
ORDER BY Revenue DESC;




/* ============================================================
   Query 13: Profit by Category

   Business Question:
   Which product categories are the most profitable?

   Objective:
   Evaluate category profitability rather than just revenue.

   Approach:
   Group transactions by Category and calculate total profit.

   Expected Outcome:
   Profit contribution of each product category.
============================================================ */

SELECT
    Category,
    ROUND(SUM(Profit), 2) AS Profit,
    ROUND(SUM(NetSales), 2) AS Revenue,
    ROUND(SUM(Profit) / SUM(NetSales) * 100, 2) AS ProfitMarginPercent
FROM vw_sales
GROUP BY Category
ORDER BY Profit DESC;



/* ============================================================
   Query 14: Top 10 Customers by Revenue

   Business Question:
   Which customers contribute the highest revenue?

   Objective:
   Identify high-value customers for retention and loyalty
   programs.

   Approach:
   Aggregate revenue by customer and sort in descending order.

   Expected Outcome:
   Top 10 revenue-generating customers.
============================================================ */

SELECT
    CustomerID,
    CONCAT(FirstName, ' ', LastName) AS CustomerName,
    ROUND(SUM(NetSales), 2) AS Revenue,
    COUNT(DISTINCT OrderID) AS Orders,
    ROUND(SUM(Profit), 2) AS Profit
FROM vw_sales
GROUP BY CustomerID, CustomerName
ORDER BY Revenue DESC
LIMIT 10;



/* ============================================================
   Query 15: Revenue by Age Group

   Business Question:
   Which customer age group contributes the most revenue?

   Objective:
   Understand purchasing behavior across different age segments.

   Approach:
   Create age groups using CASE WHEN and calculate total revenue
   for each group.

   Expected Outcome:
   Revenue contribution of each customer age segment.
============================================================ */

SELECT
    CASE
        WHEN Age BETWEEN 18 AND 25 THEN '18-25'
        WHEN Age BETWEEN 26 AND 35 THEN '26-35'
        WHEN Age BETWEEN 36 AND 45 THEN '36-45'
        WHEN Age BETWEEN 46 AND 55 THEN '46-55'
        ELSE '55+'
    END AS AgeGroup,

    ROUND(SUM(NetSales), 2) AS Revenue,
    COUNT(DISTINCT CustomerID) AS Customers,
    ROUND(AVG(NetSales), 2) AS AvgTransactionValue

FROM vw_sales
GROUP BY AgeGroup
ORDER BY Revenue DESC;




/* ============================================================
   Query 16: Customer Order Frequency

   Business Question:
   Which customers place the most orders?

   Objective:
   Identify highly engaged and repeat customers.

   Approach:
   Count distinct orders for each customer and rank them by
   order frequency.

   Expected Outcome:
   Customers with the highest number of orders.
============================================================ */

SELECT
    CustomerID,
    CONCAT(FirstName, ' ', LastName) AS CustomerName,
    COUNT(DISTINCT OrderID) AS OrderCount,
    ROUND(SUM(NetSales), 2) AS Revenue,
    ROUND(AVG(NetSales), 2) AS AvgOrderValue
FROM vw_sales
GROUP BY CustomerID, CustomerName
ORDER BY OrderCount DESC
LIMIT 10;

## Customer Analysis Insights
/*
- **Jeffrey McMahon** was identified as the highest revenue-generating customer and also had the highest number of orders, indicating a highly loyal and valuable customer relationship.
- Customers in the **55+ age group contributed the highest revenue**, suggesting that this segment has the strongest purchasing power and should be considered a priority for targeted marketing campaigns.
- The analysis showed that customer loyalty and purchase frequency can have a significant impact on overall revenue performance.
*/
/* ============================================================
   Query 17: Revenue by Region

   Business Question:
   Which regions generate the highest revenue?

   Objective:
   Compare regional sales performance and identify the strongest
   business markets.

   Approach:
   Group transactions by RegionName and calculate total revenue.

   Expected Outcome:
   Revenue generated by each region, ranked from highest to lowest.
============================================================ */

SELECT
    RegionName,
    ROUND(SUM(NetSales), 2) AS Revenue,
    COUNT(DISTINCT OrderID) AS Orders,
    COUNT(DISTINCT CustomerID) AS Customers
FROM vw_sales
GROUP BY RegionName
ORDER BY Revenue DESC;





/* ============================================================
   Query 18: Profit by Region

   Business Question:
   Which regions are the most profitable?

   Objective:
   Evaluate regional profitability and identify areas with the
   best financial performance.

   Approach:
   Group transactions by RegionName and calculate total profit
   and profit margin.

   Expected Outcome:
   Profit and profit margin for each region.
============================================================ */

SELECT
    RegionName,
    ROUND(SUM(Profit), 2) AS Profit,
    ROUND(SUM(NetSales), 2) AS Revenue,
    ROUND(SUM(Profit) / SUM(NetSales) * 100, 2) AS ProfitMarginPercent
FROM vw_sales
GROUP BY RegionName
ORDER BY Profit DESC;


/* ============================================================
   Query 19: Revenue Contribution by Region

   Business Question:
   What percentage of total revenue is contributed by each region?

   Objective:
   Understand the relative importance of each region in overall
   business performance.

   Approach:
   Calculate regional revenue and divide it by total company
   revenue using a window function.

   Expected Outcome:
   Revenue contribution percentage for each region.
============================================================ */

WITH region_revenue AS (
    SELECT
        RegionName,
        SUM(NetSales) AS Revenue
    FROM vw_sales
    GROUP BY RegionName
)

SELECT
    RegionName,
    ROUND(Revenue, 2) AS Revenue,
    ROUND(
        Revenue * 100.0 / SUM(Revenue) OVER (),
        2
    ) AS RevenueContributionPercent
FROM region_revenue
ORDER BY Revenue DESC;

## Regional Analysis Insights
/*
- The **South East region generated the highest revenue** among all business regions.
- South East contributed **15.98% of total company revenue**, making it the company’s most significant regional market.
- Regional performance analysis can help optimize inventory allocation, marketing spend, and sales resource distribution.
*/



/* ============================================================
   Query 20: Top 10 Sales Representatives by Revenue

   Business Question:
   Which sales representatives generate the highest revenue?

   Objective:
   Identify top-performing sales representatives and evaluate
   their contribution to overall sales performance.

   Approach:
   Aggregate revenue by RepName and rank in descending order.

   Expected Outcome:
   Top 10 sales representatives by revenue.
============================================================ */

SELECT
    RepName,
    ROUND(SUM(NetSales), 2) AS Revenue,
    COUNT(DISTINCT OrderID) AS OrdersHandled,
    COUNT(DISTINCT CustomerID) AS CustomersServed,
    ROUND(SUM(Profit), 2) AS Profit
FROM vw_sales
GROUP BY RepName
ORDER BY Revenue DESC
LIMIT 10;




/* ============================================================
   Query 21: Sales Representative Profitability

   Business Question:
   Which sales representatives generate the highest profit?

   Objective:
   Evaluate profitability performance, not just revenue.

   Approach:
   Aggregate profit by RepName and calculate profit margin.

   Expected Outcome:
   Profit and profit margin for each sales representative.
============================================================ */

SELECT
    RepName,
    ROUND(SUM(Profit), 2) AS Profit,
    ROUND(SUM(NetSales), 2) AS Revenue,
    ROUND(SUM(Profit) / SUM(NetSales) * 100, 2) AS ProfitMarginPercent
FROM vw_sales
GROUP BY RepName
ORDER BY Profit DESC
LIMIT 10;

## Sales Representative Performance Insights
/*
- **Ethan Adams** was identified as the top-performing sales representative.
- He generated **₹3.78M in revenue** and **₹0.99M in profit**.
- His **26.22% profit margin** indicates strong pricing discipline and a profitable sales mix.
- The alignment between high revenue and high profitability suggests that his sales approach could be used as a benchmark for other representatives.
*/



/* ============================================================
   Query 22: Rank Products by Revenue

   Business Question:
   What is the revenue ranking of each product?

   Objective:
   Compare product performance using SQL window functions.

   Approach:
   Calculate product revenue and apply the RANK() function in
   descending order of revenue.

   Expected Outcome:
   Each product with its revenue and ranking position.
============================================================ */

SELECT
    ProductName,
    Revenue,
    RANK() OVER (ORDER BY Revenue DESC) AS RevenueRank
FROM (
    SELECT
        ProductName,
        SUM(NetSales) AS Revenue
    FROM vw_sales
    GROUP BY ProductName
) t;




/* ============================================================
   Query 23: Top Product in Each Category

   Business Question:
   Which product performs best within each category?

   Objective:
   Identify category leaders using ROW_NUMBER().

   Approach:
   Rank products within each category and select the top-ranked
   product.

   Expected Outcome:
   One top-performing product for each category.
============================================================ */

WITH product_revenue AS (
    SELECT
        Category,
        ProductName,
        SUM(NetSales) AS Revenue,
        ROW_NUMBER() OVER (
            PARTITION BY Category
            ORDER BY SUM(NetSales) DESC
        ) AS rn
    FROM vw_sales
    GROUP BY Category, ProductName
)

SELECT
    Category,
    ProductName,
    ROUND(Revenue, 2) AS Revenue
FROM product_revenue
WHERE rn = 1;




/* ============================================================
   Query 24: Running Monthly Revenue

   Business Question:
   How has cumulative revenue grown over time?

   Objective:
   Track cumulative business growth month by month.

   Approach:
   Calculate monthly revenue and apply a running total using
   SUM() OVER().

   Expected Outcome:
   Monthly revenue with cumulative revenue growth.
============================================================ */

WITH monthly_revenue AS (
    SELECT
        DATE_FORMAT(OrderDate, '%Y-%m') AS Month,
        SUM(NetSales) AS Revenue
    FROM vw_sales
    GROUP BY DATE_FORMAT(OrderDate, '%Y-%m')
)

SELECT
    Month,
    ROUND(Revenue, 2) AS Revenue,
    ROUND(
        SUM(Revenue) OVER (ORDER BY Month),
        2
    ) AS RunningRevenue
FROM monthly_revenue;




/* ============================================================
   Query 25: Revenue Contribution by Category

   Business Question:
   What percentage of total revenue is contributed by each
   product category?

   Objective:
   Understand category importance in overall business revenue.

   Approach:
   Calculate category revenue and divide it by total company
   revenue using a window function.

   Expected Outcome:
   Revenue contribution percentage for each category.
============================================================ */

WITH category_revenue AS (
    SELECT
        Category,
        SUM(NetSales) AS Revenue
    FROM vw_sales
    GROUP BY Category
)

SELECT
    Category,
    ROUND(Revenue, 2) AS Revenue,
    ROUND(
        Revenue * 100.0 / SUM(Revenue) OVER (),
        2
    ) AS RevenueContributionPercent
FROM category_revenue
ORDER BY Revenue DESC;